// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUyWzdsn-9PsRcy8rCbTLwY49gQP9W1B0',
    appId: '1:952594985479:web:ec53c9f602a1bf2d5a70a2',
    messagingSenderId: '952594985479',
    projectId: 'tour-booking-ba302',
    authDomain: 'tour-booking-ba302.firebaseapp.com',
    storageBucket: 'tour-booking-ba302.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUyWzdsn-9PsRcy8rCbTLwY49gQP9W1B0',
    appId: '1:952594985479:android:ec53c9f602a1bf2d5a70a2',
    messagingSenderId: '952594985479',
    projectId: 'tour-booking-ba302',
    storageBucket: 'tour-booking-ba302.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUyWzdsn-9PsRcy8rCbTLwY49gQP9W1B0',
    appId: '1:952594985479:ios:ec53c9f602a1bf2d5a70a2',
    messagingSenderId: '952594985479',
    projectId: 'tour-booking-ba302',
    storageBucket: 'tour-booking-ba302.firebasestorage.app',
    iosBundleId: 'com.example.project_capstone_prm393_group_1_se1890',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUyWzdsn-9PsRcy8rCbTLwY49gQP9W1B0',
    appId: '1:952594985479:ios:ec53c9f602a1bf2d5a70a2',
    messagingSenderId: '952594985479',
    projectId: 'tour-booking-ba302',
    storageBucket: 'tour-booking-ba302.firebasestorage.app',
    iosBundleId: 'com.example.project_capstone_prm393_group_1_se1890',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUyWzdsn-9PsRcy8rCbTLwY49gQP9W1B0',
    appId: '1:952594985479:web:ec53c9f602a1bf2d5a70a2',
    messagingSenderId: '952594985479',
    projectId: 'tour-booking-ba302',
    authDomain: 'tour-booking-ba302.firebaseapp.com',
    storageBucket: 'tour-booking-ba302.firebasestorage.app',
  );
}
