// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjJK7ul2kcIuYo8UG5eCS8VKw_0Faql1M',
    appId: '1:788224320201:web:7b51b8d8ababe3d6fda318',
    messagingSenderId: '788224320201',
    projectId: 'tourbookingapp-cf9d9',
    authDomain: 'tourbookingapp-cf9d9.firebaseapp.com',
    storageBucket: 'tourbookingapp-cf9d9.firebasestorage.app',
    measurementId: 'G-TC9LT82D9Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlN-ixpaJwyh9jWFb83uMcmd1_TRL5BD0',
    appId: '1:788224320201:android:af2ece6082e64962fda318',
    messagingSenderId: '788224320201',
    projectId: 'tourbookingapp-cf9d9',
    storageBucket: 'tourbookingapp-cf9d9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiFHUAJ5OeJ8x7Layd_rOL7KudE15b2F0',
    appId: '1:788224320201:ios:28f8ab39c3acc31ffda318',
    messagingSenderId: '788224320201',
    projectId: 'tourbookingapp-cf9d9',
    storageBucket: 'tourbookingapp-cf9d9.firebasestorage.app',
    iosBundleId: 'com.example.projectCapstonePrm393Group1Se1890',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiFHUAJ5OeJ8x7Layd_rOL7KudE15b2F0',
    appId: '1:788224320201:ios:28f8ab39c3acc31ffda318',
    messagingSenderId: '788224320201',
    projectId: 'tourbookingapp-cf9d9',
    storageBucket: 'tourbookingapp-cf9d9.firebasestorage.app',
    iosBundleId: 'com.example.projectCapstonePrm393Group1Se1890',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjJK7ul2kcIuYo8UG5eCS8VKw_0Faql1M',
    appId: '1:788224320201:web:dcb62cd76903bfa4fda318',
    messagingSenderId: '788224320201',
    projectId: 'tourbookingapp-cf9d9',
    authDomain: 'tourbookingapp-cf9d9.firebaseapp.com',
    storageBucket: 'tourbookingapp-cf9d9.firebasestorage.app',
    measurementId: 'G-S77TLSMXN8',
  );
}
